
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Angel
 */
public class Ventana extends javax.swing.JFrame {

    private Producto[] P = new Producto[100];
    private int tope = 0,id = 1;
    DefaultTableModel m;
    
    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        m = (DefaultTableModel) tblProducto.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        lblNombreP = new javax.swing.JLabel();
        jtfNombreP = new javax.swing.JTextField();
        lblValorP = new javax.swing.JLabel();
        spnValor = new javax.swing.JSpinner();
        cmbDivisa = new javax.swing.JComboBox<>();
        btnAgregarProducto = new javax.swing.JButton();
        jspTabla = new javax.swing.JScrollPane();
        tblProducto = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(581, 459));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Agregar Producto"));
        jPanel1.setMinimumSize(new java.awt.Dimension(353, 70));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        lblNombreP.setText("Nombre:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(lblNombreP, gridBagConstraints);

        jtfNombreP.setMinimumSize(new java.awt.Dimension(60, 20));
        jtfNombreP.setPreferredSize(new java.awt.Dimension(90, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(jtfNombreP, gridBagConstraints);

        lblValorP.setText("Valor:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(lblValorP, gridBagConstraints);

        spnValor.setModel(new javax.swing.SpinnerNumberModel(0.0f, 0.0f, null, 0.5f));
        spnValor.setMinimumSize(new java.awt.Dimension(60, 20));
        spnValor.setPreferredSize(spnValor.getMinimumSize());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(spnValor, gridBagConstraints);

        cmbDivisa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Peso (MXN)", "Dolar (USA)", "Euro", "Libra Esterlina", "Yen Japonés", "Franco Suizo" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(cmbDivisa, gridBagConstraints);

        btnAgregarProducto.setText("Agregar Producto");
        btnAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.weightx = 1.0;
        jPanel1.add(btnAgregarProducto, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 20);
        getContentPane().add(jPanel1, gridBagConstraints);

        tblProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre del producto", "Valor", "ID"
            }
        ));
        jspTabla.setViewportView(tblProducto);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        getContentPane().add(jspTabla, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductoActionPerformed
        try {
            if (jtfNombreP.getText().equals("") || (float)(spnValor.getValue()) == 0)
                throw new Exception("Completa los valores del producto antes de insertar");
            TIPO_DIVISA t = null;
            switch (cmbDivisa.getSelectedIndex()) {

                case 0:
                    t = TIPO_DIVISA.Peso;
                    break;
                case 1:
                    t = TIPO_DIVISA.Dolar;
                    break;
                case 2:
                    t = TIPO_DIVISA.Euro;
                    break;
                case 3:
                    t = TIPO_DIVISA.LibraEsterlina;
                    break;
                case 4:
                    t = TIPO_DIVISA.YenJaponés;
                    break;
                case 5:
                    t = TIPO_DIVISA.FrancoSuizo;
                    break;
                default:
            }
            Producto p = new Producto(jtfNombreP.getText(), (float)(spnValor.getValue()),t);
            P[tope++] = p;
            m.addRow(new Object[]{p.getNombre(),p.getValS(),id++});
        } catch (Exception e) {
            showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_btnAgregarProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarProducto;
    private javax.swing.JComboBox<String> cmbDivisa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jspTabla;
    private javax.swing.JTextField jtfNombreP;
    private javax.swing.JLabel lblNombreP;
    private javax.swing.JLabel lblValorP;
    private javax.swing.JSpinner spnValor;
    private javax.swing.JTable tblProducto;
    // End of variables declaration//GEN-END:variables
}
